---
title: "OpenStack Management Network Traffic Report"
author: Adnei W. Donatti
date: May 27, 2020
output:
  pdf_document:
    fig_caption: true
    keep_tex: true
    latex_engine: pdflatex
fontsize: 12pt
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{float}
  - \floatplacement{figure}{H}
---

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.pos = 'H')
  source('linear_regression.R')
  library(magrittr)
  library(knitr)
  library(kableExtra)
  library(ggplot2)
  library(dplyr)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis', fig.align="center"}

col_arr <- c('#0000cc', '#6600ff', '#006600', '#cc9900', '#ff3300')
for(operation in objects.operations){
  print(operation)
  print('')
  op_lr.df <- lr.df[lr.df$operation == operation, ]
  op_lr.df$image_size = as.numeric(op_lr.df$image_size)
  op_lr.df$mean_total_traffic = as.numeric(op_lr.df$mean_total_traffic)
  adjust <- lm(op_lr.df$mean_total_traffic ~ op_lr.df$image_size)
  fit_adjust <- fitted(adjust)
  resid_adjust <- resid(adjust)
  print(summary(adjust))
  cfnt_adjust <- confint(adjust, level=0.9)
  corr <- cor(op_lr.df$image_size, op_lr.df$mean_total_traffic)
  corr2 <- corr^2
  plot(op_lr.df$image_size, op_lr.df$mean_total_traffic, pch=20, xlab="Image size (MB)", ylab="Traffic Volume (MB)", col=col_arr)
  text(op_lr.df$image_size, op_lr.df$mean_total_traffic, labels=op_lr.df$image, cex= 0.9, pos=c(2,4)) #pos=c(1,1,3,4,3)
  abline(adjust, col="red")
}




  }




```
