---
title: "OpenStack Management Network Traffic Report"
author: Adnei W. Donatti
date: May 27, 2020
output:
  pdf_document:
    fig_caption: true
    keep_tex: true
    latex_engine: pdflatex
fontsize: 12pt
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{float}
  - \floatplacement{figure}{H}
---

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(fig.pos = 'H')
  source('linear_regression/linear_regression.R')
  library(magrittr)
  library(knitr)
  library(kableExtra)
  library(ggplot2)
  library(dplyr)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, results='asis', fig.align="center"}
  filtered_op <- objects.operations[objects.operations == 'CREATE' | objects.operations == 'SHELVE']
  lr_stats.list <- list(operation = vector('list', length(filtered_op)),
                            adjust = vector('list', length(filtered_op)),
                            resid = vector('list', length(filtered_op)),
                            confint = vector('list', length(filtered_op)))
  col_arr <- c('#0000cc', '#6600ff', '#006600', '#cc9900', '#ff3300')
  op_count <- 0
  for(operation in filtered_op){
    op_count <- op_count + 1
    ############ REMOVING RAW IMAGE ############
    op_lr.df <- lr.df[lr.df$operation == operation & lr.df$image != 'debian10raw', ]
    op_lr.df$image_size = as.numeric(op_lr.df$image_size)
    op_lr.df$mean_total_traffic = as.numeric(op_lr.df$mean_total_traffic)
    adjust <- lm(op_lr.df$mean_total_traffic ~ op_lr.df$image_size)
    fit_adjust <- fitted(adjust)
    resid_adjust <- resid(adjust)
    cfnt_adjust <- confint(adjust, level=0.9)
    corr <- cor(op_lr.df$image_size, op_lr.df$mean_total_traffic)
    corr2 <- corr^2
    title <- paste('Linear Regression Model:', operation)
    lr_stats.list$operation[[op_count]] <- operation
    lr_stats.list$adjust[[op_count]] <- adjust
    lr_stats.list$resid[[op_count]] <- resid_adjust
    lr_stats.list$confint[[op_count]] <- cfnt_adjust
    lr.plot <- ggplot(op_lr.df, aes(image_size, mean_total_traffic)) +
    geom_point(aes(color=image)) +
    geom_smooth(method = "lm", level = 0.90,  formula = y ~ x) +
    ylab("Traffic Volume (MB)") +
    xlab("Image Size (MB)") +
    ggtitle(title)
    print(lr.plot)
  }
```


```{r echo=FALSE, eval=TRUE, warning=FALSE, message=TRUE, comment=""}
  for(op_count in c(1:length(filtered_op))){
    print(lr_stats.list$operation[[op_count]])
    print(summary(lr_stats.list$adjust[[op_count]]))
    print(lr_stats.list$resid[[op_count]])
    print(lr_stats.list$confint[[op_count]])
    cat("\n")
  }

```
